export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOCAL_LOGIN = 'LOCAL_LOGIN';

export const INCREASE_COUNT_PEOPLE = 'INCREASE_COUNT_PEOPLE';
export const SAVE_HOUSEHOLD_SUCCESS = 'SAVE_HOUSEHOLD_SUCCESS';
export const SAVE_HOUSEHOLD_FAIL = 'SAVE_HOUSEHOLD_FAIL';
export const FIRST_HOUSEHOLD_SAVE = 'FIRST_HOUSEHOLD_SAVE';
export const GET_HOUSEHOLD_SUCCESS = 'GET_HOUSEHOLD_SUCCESS';
export const GET_HOUSEHOLD_FAIL = 'GET_HOUSEHOLD_FAIL';

export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAIL = 'SAVE_PERSON_FAIL';
