export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_COMPLETE = 'SIGNUP_COMPLETE';
export const CLEAR_USER_MESSAGE= 'CLEAR_USER_MESSAGE';

export const LOCAL_LOGIN = 'LOCAL_LOGIN';

export const INCREASE_COUNT_PEOPLE = 'INCREASE_COUNT_PEOPLE';
export const SAVE_HOUSEHOLD_SUCCESS = 'SAVE_HOUSEHOLD_SUCCESS';
export const SAVE_HOUSEHOLD_FAIL = 'SAVE_HOUSEHOLD_FAIL';
export const FIRST_HOUSEHOLD_SAVE = 'FIRST_HOUSEHOLD_SAVE';
export const GET_HOUSEHOLD_SUCCESS = 'GET_HOUSEHOLD_SUCCESS';
export const GET_HOUSEHOLD_FAIL = 'GET_HOUSEHOLD_FAIL';
export const GET_USAGES_SUCCESS = 'GET_USAGES_SUCCESS';
export const GET_USAGES_FAIL = 'GET_USAGES_FAIL';
export const SAVE_USAGE_SUCCESS = 'SAVE_USAGE_SUCCESS';
export const SAVE_USAGE_FAIL = 'SAVE_USAGE_FAIL';
export const DELETE_USAGE_SUCCESS = 'DELETE_USAGE_SUCCESS';
export const DELETE_USAGE_FAIL = 'DELETE_USAGE_FAIL';
export const CLEAR_HOUSEHOLD_MESSAGE = 'CLEAR_HOUSEHOLD_MESSAGE';

export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAIL = 'SAVE_PERSON_FAIL';
